name: dot_indication_flutter
description: Widget to display page dots indicator to show a position for a Page View Scroll
version: 0.0.1
homepage: https://github.com/SanchitSaran/FlutterDotsIndicator.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  plugin:
    platforms:
      android:
        package: com.example.dot_indication_flutter
        pluginClass: DotIndicationFlutterPlugin
      ios:
        pluginClass: DotIndicationFlutterPlugin


